uuaa: gdpd
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  path: ${LOG_PATH:.}
  level:
    ROOT: INFO
server:
  port: ${NOVA_PORT:8083}
gdpd:
  batch:
    service-url: ${BATCH_SERVICE_URL:http://localhost:8082}
