uuaa: gdpd
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  path: ${LOG_PATH:.}
  level:
    ROOT: INFO
    com.bbva.gdpd: DEBUG
server:
  port: ${NOVA_PORT:8082}
spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5555/gdpddb
    username: nova
    password: nova
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
batch:
  output:
    path: ${BATCH_OUTPUT_PATH:/tmp/gdpd-reports}
