spring:
  application:
    name: gdpd-batch-reportes
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true
  batch:
    jdbc:
      initialize-database: never
    job:
      enabled: false
      names: generarReporteDiario

# Actuator: Health Check, Metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 9081

---
spring:
  config:
    activate:
      on-profile: dev,int
  datasource:
    url: jdbc:postgresql://localhost:5555/gdpddb
    username: nova
    password: nova
    hikari:
      maximum-pool-size: 5

logging:
  level:
    root: INFO
    com.bbva.gdpd: DEBUG

---
spring:
  config:
    activate:
      on-profile: pre,pro
  datasource:
    url: jdbc:postgresql://db-${spring.profiles.active}.nova:5432/gdpddb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

logging:
  level:
    root: WARN
    com.bbva.gdpd: INFO
