server:
  port: 8080

spring:
  application:
    name: gdpd-pedidos-api
  datasource:
    url: jdbc:postgresql://localhost:5432/novadb
    username: nova
    password: nova
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        pedidos-out-0:
          destination: pedidos.eventos
          content-type: application/json
      rabbit:
        bindings:
          pedidos-out-0:
            producer:
              auto-bind-dlq: true
              republish-to-dlq: true
    config:
      enabled: false
  sleuth:
    sampler:
      rate: 1.0
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env,refresh
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        step: 30s
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 500ms,1s,2s

logging:
  pattern:
    level: "%5p [%X{traceId},%X{spanId}]"
  level:
    com.bbva.gdpd: DEBUG
